### ISSUE TITLE
openai apikey can use ollama？

### ISSUE THREAD

**Issue by lonngxiang** [AmyangXYZ/AniMate#1]

**Comment by AmyangXYZ** [comment]
You can modify this [code](https://github.com/AmyangXYZ/AniMate/blob/main/src/renderer/src/hooks/useOpenAI.ts)

**Comment by AmyangXYZ** [comment]
Will add ollama in new projects https://github.com/AmyangXYZ/MiKaPo and https://github.com/AmyangXYZ/MiKaPo-Electron
